language: go
go:
  - tip
env:
  - GO111MODULE=on
install:
  - go get -v golang.org/x/lint/golint
script:
  #- golint -set_exit_status . # пока закоментил
  - go test -v -race .
matrix:
  allow_failures:
    - go: tip
notifications:
    email: false